### ISSUE TITLE
Problem with accounts endpoint

### ISSUE THREAD

**Issue by misticini** [nylas/nylas-nodejs#1]
Hello,

I'm using Nylas-nodejs sdk and i've detected a bug. 

I'm trying to get the accounts with:

```
Nylas.with(ApiToken).accounts.list().then(function(accounts) {
}); 
```
But this functionality have a bunch of bugs. I've patch the NylasSDK but only on Javascript source (not on coffeescript) but i will list the problems that make this not work:

1- 

On management-model-collection.js the code was:
```
ManagementModelCollection.prototype.path = function() {
      return "/a/" + this.api.appId+ "/accounts";
    };
```
This not work because api isnt a defined attribute.

I've patched this to:

```
ManagementModelCollection.prototype.path = function() {
      Nylas = require('../nylas');
      return "/a/" + Nylas.appId+ "/accounts";
    };
```

2- 
On nylas-connection.js the code on line 41 was:
```
if (options.json == null) {
        options.json = true;
      }
 if (this.accessToken) {
        options.auth = {
          'user': this.accessToken,
          'pass': '',
          'sendImmediately': true
        };
}
```
I've patched this  to:

```
if (options.json == null) {
        options.json = true;
      }
      if (options.path.substr(0,3) === '/a/' ) {
        options.auth = {
          'user': Nylas.appSecret,
          'pass': '',
          'sendImmediately': true
        };
      }
      else if (this.accessToken) {
        options.auth = {
          'user': this.accessToken,
          'pass': '',
          'sendImmediately': true
        };
      }
```

I can made a patch in coffeescript source and make a pull request, but i think that with all explained its better to nylas team corrected this bug on your way :)

Regards

**Comment by bengotow** [comment]
Hi @misticini thanks for reporting these issues! I'll take a look. In #1, it looks like the path should reference `this.connection` and not `this.api`. I think in the second one you're totally right—the access token is used for most requests, but the accounts endpoint uses the app secret. I can modify the coffeescript and add test cases for these. Stay tuned!

**Comment by misticini** [comment]
Hello Ben,

it's a pleasure helping this awesome project. I'm using nilas in my MSc Thesis, and maybe i can helping in anything else if i found another bug or if i made any development on Node-js sdk :)

Regards

**Comment by jstejada** [comment]
This should be fixed with https://github.com/nylas/nylas-nodejs/commit/38839d44622879cece6a9e93a47f9639197b8570
