### ISSUE TITLE
drafts.build({}).send() on an existing thread requires threadId, not thread_id

### ISSUE THREAD

**Issue by trever** [nylas/nylas-nodejs#10]
The build method accepts a `threadId` parameter instead of a `thread_id`, yet there's no documentation to reflect that. Seems unnecessary to be inconsistent with the API documentation. 

I would recommend changing threadId to thread_id.

https://github.com/nylas/nylas-nodejs/blob/5cab5b37bb89b03a2e361c01ae276eb2100b8a64/lib/models/message.js#L56

**Comment by trever** [comment]
Additionally, the `send

**Comment by khamidou** [comment]
Regarding #1 --- we use camelCase throughout the SDK so we're not going to change the casing of `threadId`

Regarding `reply_to_message_id`, good catch! I've just sent for review a patch to fix this.

Karim
