### ISSUE TITLE
Incorrect file size and contents

### ISSUE THREAD

**Issue by elmeister** [nylas/nylas-nodejs#119]
Hello!
Thanks for the awesome module!
Tho we experience some difficulties and need some help.
When we upload files using the `upload` method of the object, created by `nylas.drafts.build`, resulting file have incorrect size and content - when downloaded or attached to messages.
```javascript
const fs = require('fs');
fs.readFile(filePath, 'utf8', function (err, data) {
  const file = nylas.files.build({
    filename,
    data,
    contentType: 'application/pdf',
  });

  file.upload(function(err, uploadedFile) {
    const fileToDownload = nylas.files.build({
      id: uploadedFile.id,
    });
    fileToDownload.download((err, file) => {
      fs.writeFile(`copy_${filename}`, file.body);
    });
  });
});
```
When this code is executed, downloaded file has different size (in our case 282 Kb instead of initial 162 Kb) and resulting PDF consist of two pages (same as initial file), but these pages are just empty.
Same happens when we attach files to messages - empty PDFs with incorrect size are attached.
Please help us to find out what we could miss to let files will have correct size and contents.

**Comment by Gerdie** [comment]
@elmeister can you try again, and omit the 'utf8' param from `fs.readFile` when uploading a PDF?

**Comment by Gerdie** [comment]
Closing this, please re-open with more details if you are still running into this.
