### ISSUE TITLE
Creating & Updating events only supports start_time and end_time

### ISSUE THREAD

**Issue by smrutherford** [nylas/nylas-nodejs#146]
Needs to support the other available options for the `when` attribute:

-time
-date
-start_date and end_date

**Comment by jasonbreault** [comment]
As expected with the creating a new event, (by passing in the "when" object), when updating an existing event, the event.save() function should support update the date/time of the object by passing the following when object (as stated by Nylas docs):

   when: {
      start_time: <unix time format>,
      end_time: <unix time format>
   }

   when: {
      start_date: <YYYY-MM-DD format>,
      end_date: < YYYY-MM-DD format>
   }
 
when: {
   date: <YYYY-MM-DD format>
   }

**Comment by smrutherford** [comment]
Hi @jasonbreault, thanks again for reporting this issue. We've released a fix and it is now available in the latest NodeSDK v4.8.0. Now, you may create or update events by either assigning the `start` and `end` params or by assigning the `when` parameter.
