### ISSUE TITLE
Fetch Multiple Records by ID

### ISSUE THREAD

**Issue by KeKs0r** [nylas/nylas-nodejs#147]
Hi, I was wondering if it's possible to fetch multiple records by id?

This is in particular helpful for my receiving webhooks, since initial sync, might send deltas with up to 500 messages. Which in order to process I am currently all looking up individually (500 requests to fetch the message by ID). I was wondering, if it is possible to get all those 500 messages by ID with a single call?

**Comment by smrutherford** [comment]
Hi @KeKs0r! 

Unfortunately, the Nylas API only has the functionality to fetch one message by ID. For initial sync, I recommend listening to deltas while paginating through `/threads`. More about this and other recommended sync strategies is provided in our docs [here](https://docs.nylas.com/docs/sync-strategies).

If you would like to request fetching multiple objects by ID, though, you may submit a feature request to our product team [here](https://portal.productboard.com/nylas/1-nylas-product-roadmap/tabs/2-under-consideration). Simply click the Submit Idea button in the upper right hand corner!

Thanks,
Stacey
