### ISSUE TITLE
Update an existing event identified by the specified event ID

### ISSUE THREAD

**Issue by elmeister** [nylas/nylas-nodejs#159]
Hello!
As mentioned in https://docs.nylas.com/reference#eventsid, there should be an `update method for events, identified by the specified event ID`. But the API documentation for PUT seems to be the copy-paste of the POST method, with the changed first line. Could you please provide code sample how to update an event by its ID without retrieving it from API first?

**Comment by elmeister** [comment]
Actually the following code seems to work fine, so the question isn't actual any more
```JS
const nylasEvent = nylas.events.build({
  id: calendarEvent.externalId,
  ...update,
});
await nylasEvent.save();
```
Though probably it's still actual to review the API sample.

**Comment by BenLloydPearson** [comment]
Hi @elmeister,

I'm not totally sure if I understand your issue. Is there a reason you can't use the `.find('{id}')` method to get the event you want to modify?

For example:

`nylas.events.find('{id}').then(resp => event = resp);`

**Comment by elmeister** [comment]
Hi @BenLloydPearson,
We don't really need to get an event from the server before update, we just need to update it without extra API calls to retrieve it first, we already have all information we need.
