### ISSUE TITLE
Filter + limit

### ISSUE THREAD

**Issue by AdriVanHoudt** [nylas/nylas-nodejs#16]
Unless I am doing something wrong it is not possible to both use a filter (`list`) and limit (`range`) in 1 call?
List will always ask for EVERYTHING see https://github.com/nylas/nylas-nodejs/blob/master/models/restful-model-collection.coffee#L51
Afaik this even violates the docs stating that the max limit on fetching messages is 100 (I just pulled in 1400 in one call)

**Comment by khamidou** [comment]
Good catch! I'll try to fix this next week. 

> Afaik this even violates the docs stating that the max limit on fetching messages is 100 (I just pulled in 1400 in one call)
By the way, the API limits requests to 500 messages (IIRC) but the SDK does multiple calls to the API behind the scenes and aggregates them.

Karim

**Comment by AdriVanHoudt** [comment]
i could only find default limit of a 100 in the docs that's why

**Comment by khamidou** [comment]
Fixed in e975ee20d37b.
