### ISSUE TITLE
Cors  errors.

### ISSUE THREAD

**Issue by juanjoFactoria** [nylas/nylas-nodejs#160]
We are trying to apply this package to vuejs. But we have problems with CORS.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.nylas.com/connect. (Reason: CORS preflight channel did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.nylas.com/connect. (Reason: CORS request did not succeed).
Error: Network Error

Can someone help us.

**Comment by BenLloydPearson** [comment]
Hello @juanjoFactoria, please reach out to Nylas support (support@nylas.com) to get help with this issue.
