### ISSUE TITLE
Nylas client crashing node on invalid requests

### ISSUE THREAD

**Issue by Pagebakers** [nylas/nylas-nodejs#172]
Nylas intermittendly makes our nodes apps crash, even though we have proper error handling.
There seems to be an issue in the client when requests timeout or fail.

Here's a excerpt of the error

"at Request._callback ([..]/node_modules/nylas/lib/nylas-connection.js:177:37)"
TypeError: Cannot read property 'headers' of undefined" 

I'm not sure how to reproduce this and which request is causing this.

The error is happening both on our webhook handers and when sending messages through the api.

**Comment by Gerdie** [comment]
Thanks for reporting @Pagebakers we'll look into this.

**Comment by Pagebakers** [comment]
Any updates on this? this is a real serious issue, it's causing quite a lot of crashes.

**Comment by Pagebakers** [comment]
To help you along a bit...

https://github.com/nylas/nylas-nodejs/blob/master/src/nylas-connection.js#L133

The response needs to be checked, as it can be undefined

**Comment by Gerdie** [comment]
Thanks @Pagebakers feel free to review https://github.com/nylas/nylas-nodejs/pull/177 and let us know if more information in the error message would be useful.

**Comment by Gerdie** [comment]
This was resolved and released yesterday in v4.10.1
