### ISSUE TITLE
Replace deprecated "request"

### ISSUE THREAD

**Issue by TrySound** [nylas/nylas-nodejs#174]
"request" package is deprecated.

https://github.com/request/request#deprecated

A few possible alternatives
- https://github.com/node-fetch/node-fetch
- https://github.com/axios/axios
- https://github.com/sindresorhus/got

**Comment by Gerdie** [comment]
Thanks for reporting, @TrySound

**Comment by TrySound** [comment]
FYI I'm working on this.

**Comment by mrashed-dev** [comment]
`node-fetch` has completely replaced the `request` library, will be available in next release.
