### ISSUE TITLE
Missing info on how to setup webhook endpoint in documentation

### ISSUE THREAD

**Issue by victorbojica** [nylas/nylas-nodejs#206]
Hello 

I've been trying to setup an webhook for the past few hours. 
I kept getting this error:
```
{
  "message": "Failed to verify challenge string. Please refer to our documentation for more information: https://docs.nylas.com/reference#section-verification-request",
  "type": "invalid_request_error"
}
```

The problem is that the link in the response is broken.

I've managed to finally set up the endpoint by finding this piece of code. 
https://github.com/nylas/nylas-nodejs/blob/5bd47fd4dee08f7937251c042914daf7f5f24cda/example/webhooks/index.js#L39

I think it would be very important to have this in the documentation. And also explain the webhook endpoint verification process.

Thanks
Victor

**Comment by jhatch28** [comment]
Hey @victorbojica thanks for pointing this out, the person that's in charge of our documentation is aware and has added this to their to do list.

**Comment by BenLloydPearson** [comment]
@victorbojica the docs referenced in that error have been moved here: https://docs.nylas.com/docs/webhooks-overview#verification-request

**Comment by mrashed-dev** [comment]
Closing this issue as the documentation link returned by the API is the correct one now, and contains more information on how to set up a webhook as well as the challenge verification string.
