### ISSUE TITLE
error in importing nylas in typescript project 

### ISSUE THREAD

**Issue by RezaRahmati** [nylas/nylas-nodejs#207]
Hi

I tried to import nylas to my NestJs project (which is using Typescript) and I get this error

`import * as Nylas from 'nylas';`

> This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export

and also `import { Nylas } from 'nylas'` doesnt work neither.

The only option was turning on esModuleInterop which I got weired compile error on some other part project (which was compiling fine before) or importing like below

`import Nylas = require('nylas/lib/nylas');`

**Comment by BenLloydPearson** [comment]
@RezaRahmati Can you verify that your environment meets all of the required versions for the SDK's dependencies? They are listed in the root level [package.json](https://github.com/nylas/nylas-nodejs/blob/main/package.json) file:

`  "dependencies": {
    "JSONStream": "^1.3.5",
    "async": "^2.6.2",
    "backoff": "^2.5.0",
    "request": "^2.88.0"
  },`

Also, can you provide your complete logs? That would help us identify the problem.

**Comment by dereekb** [comment]
Running into the same thing on a NestJS project.

Using `import Nylas from 'nylas';` seems to only import the typings, but Nylas itself in the code is undefined. When I use `const Nylas = require('nylas')` it resolves properly.


```
import Nylas from 'nylas';
const NylasClient = require('nylas');

@Injectable()
export class NylasApi {

  constructor(configService: ConfigService) {
    const clientId = configService.get<string>('NYLAS_CLIENT_ID');
    const clientSecret = configService.get<string>('NYLAS_CLIENT_SECRET');

    console.log('Nylas: ', Nylas);
    console.log('NylasClient: ', NylasClient);
  }

}
```

The console.log outputs here output:

```
Nylas:  undefined
NylasClient:  [Function: Nylas] { ... }
```

Here's the dependencies that were pulled down for each of those in my package-lock.json:

```
    "JSONStream": {
      "version": "1.3.5",
      "resolved": "https://registry.npmjs.org/JSONStream/-/JSONStream-1.3.5.tgz",
      "integrity": "sha512-E+iruNOY8VV9s4JEbe1aNEm6MiszPRr/UfcHMz0TQh1BXSxHK+ASV1R6W4HpjBhSeS+54PIsAMCBmwD06LLsqQ=="
    },
    "async": {
      "version": "2.6.3",
      "resolved": "https://registry.npmjs.org/async/-/async-2.6.3.tgz",
      "integrity": "sha512-zflvls11DCy+dQWzTW2dzuilv8Z5X/pjfmZOWba6TNIVDm+2UDaJmXSOXlasHKfNBs8oo3M0aT50fDEWfKZjXg=="
    },
    "backoff": {
      "version": "2.5.0",
      "resolved": "https://registry.npmjs.org/backoff/-/backoff-2.5.0.tgz",
      "integrity": "sha1-9hbtqdPktmuMp/ynn2lXIsX44m8="
    },
"request": {
      "version": "2.88.2",
}
...
```

My guess is it is due to nylas-nodejs's tsconfig having esModuleInterop=true, which I believe changes the way the project is built.

As a temporary workaround I created a new typescript file and typing:

```
import Account from 'nylas/lib/models/account';
import Connect from 'nylas/lib/models/connect';
import ManagementAccount from 'nylas/lib/models/management-account';
import ManagementModelCollection from 'nylas/lib/models/management-model-collection';
import RestfulModelCollection from 'nylas/lib/models/restful-model-collection';
import Webhook from 'nylas/lib/models/webhook';
import NylasConnection from 'nylas/lib/nylas-connection';

const Nylas: NylasClient = require('nylas');

export interface NylasClient {
  clientId: string;
  clientSecret: string;
  apiServer?: string | null;
  accounts?: ManagementModelCollection<ManagementAccount> | RestfulModelCollection<Account>;
  connect?: Connect;
  webhooks?: ManagementModelCollection<Webhook>;
  config({ clientId, clientSecret, apiServer, appId, appSecret }: {
    clientId: string;
    clientSecret: string;
    apiServer?: string;
    appId?: string;
    appSecret?: string;
  }): NylasClient;
  clientCredentials(): boolean;
  with(accessToken: string): NylasConnection;
  application(options?: {
    application_name?: string;
    redirect_uris?: string[];
    applicationName?: string;
    redirectUris?: string[];
  }): Promise<any>;
  exchangeCodeForToken(code: string, callback?: (error: Error | null, accessToken?: string) => void): Promise<string>;
  urlForAuthentication(options?: {
    redirectURI?: string;
    loginHint?: string;
    state?: string;
    scopes?: string[];
  }): string;
}

export { Nylas };
```

**Comment by Gerdie** [comment]
Hi @RezaRahmati we recommend the following:

`const Nylas = require('nylas');`
or
`import Nylas = require('nylas');`

as we use the `export = ` CommonJS syntax. See: related [Typsecript docs](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require). Please re-open this issue if this does not resolve your error.
