### ISSUE TITLE
Question: Calendar availability endpoint support

### ISSUE THREAD

**Issue by mreilly-lula** [nylas/nylas-nodejs#215]
Hello, I noticed the `/calendars/availability` and `/calendars/availability/consecutive` endpoints are not covered in the node SDK. Is there a technical reason for this? I have written code to accomplish these requests on my end, would the Nylas team be open to a PR that adds them to this repo?

Thank you!

**Comment by mrashed-dev** [comment]
You are more than welcome to submit a PR! We welcome any addition to improving our SDKs :)
