### ISSUE TITLE
Question: How best to get typings from this library

### ISSUE THREAD

**Issue by jtushman** [nylas/nylas-nodejs#217]
Hi friends,

We are integrating with Nylas now, and we are Typescript shop.  I was wondering how other typescript implementors have gotten types to work.

right now I do something like:

```typescript
const NylasClient = require('nylas')

const account = await NylasClient.with(token).account.get()

```

and account is coming back as 'any', I would expect and love to see that as Nylas.Account or the like

i see that the library does have types internally at: models/account.d.ts

this is just one example would love to have access to all of the main object types without me needed to create an additional layer of abstraction.

Thanks!

**Comment by sdwvit** [comment]
Probably just need an option in tsconfig to output d.ts files for publishing. Something like `compilerOptions.declaration: true`

**Comment by dereekb** [comment]
A number of types come back as RestfulModelCollection or RestfulModelInstance, so I've still been using the "as" keyword.

```
import Calendar from 'nylas/lib/models/calendar';

...

  async loadAccount(): Promise<Account> {
    return this.connection.account.get() as Promise<Account>;
  }

```

I am still using this workaround too. I can't remember if this is necessary, but this may help you access the types better:

https://github.com/nylas/nylas-nodejs/issues/207#issuecomment-727336626

**Comment by mrashed-dev** [comment]
Looking into this issue as well, it looks very similar to the problems raised in #224.

**Comment by mrashed-dev** [comment]
#238 should fix this issue, and it will be part of the next SDK release. Please re-open if the same issue persists after the upgrade!
