### ISSUE TITLE
Seems like Nylas.with(x).account.get() should return an Account

### ISSUE THREAD

**Issue by asktree** [nylas/nylas-nodejs#224]
Current behavior:
`Nylas.with(x).account.get()` has type `RestfulModel`

Expected behavior:
`Nylas.with(x).account.get()` has type `Account`

Also, check out this sad code I had to write to avoid runtime errors:

```ts
// Tell Nylas to cancel the account...
const account = await Nylas.with(instructor.nylasAccessToken).account.get();
// Nylas SDK is uhh so I have to do this 
const accountAgain = await Nylas.accounts.find(account.id);
await accountAgain.downgrade();
```

**Comment by asktree** [comment]
Likewise `nylas.calendars.list()` would seemingly return `Calendar[]`

**Comment by mrashed-dev** [comment]
Thanks for bringing this to our attention, we are currently looking at this issue!

**Comment by mrashed-dev** [comment]
#238 should fix this issue, and it will be part of the next SDK release. Please re-open if the same issue persists after the upgrade!
