### ISSUE TITLE
Bug: Draft Tracking Content Not Passed To Send()

### ISSUE THREAD

**Issue by dereekb** [nylas/nylas-nodejs#231]
Drafts that are loaded and then have send() called on them do not include the tracking code.

```
const draft = await this.connection.drafts.find(nylasDraftId) as Promise<Draft>;
const tracking = { "links": true, "opens": true, "thread_replies": true };
await draft.send(tracking);
```

It looks like this is the line to blame:
https://github.com/nylas/nylas-nodejs/blob/8c7e4275a696e7eb592509b7bb5afe0189d45a91/src/models/draft.ts#L85

When id is set (set on loading a Draft or other method where this.id is set) the tracking is not included.

Expected behavior is the trackingArg be added to the request body.

### Workaround
No workaround available when using Draft model directly. Need to use axios/etc. to performing a POST request directly to the send endpoint. The request is simple though:

POST to https://api.nylas.com/send

```
{
  "draft_id": "mydraftid",
  "version": 0,
  "tracking": { "links": true, "opens": true, "thread_replies": true }
}
```

Result can be wrapped into a message:

```
const result = await this.postToNylas({
      url: 'https://api.nylas.com/send', body: {
        draft_id: request.id,
        version: request.version,
        tracking: request.tracking
      }
    });

    return new Message(this.connection, result);
```

**Comment by mrashed-dev** [comment]
Thanks for reporting this issue, we are investigating it!

**Comment by mrashed-dev** [comment]
The `tracking` object was not being added to an already-existing `draft` object, but that's now fixed and will be available in the next release!
