### ISSUE TITLE
Use native URL

### ISSUE THREAD

**Issue by AvivonCtrl** [nylas/nylas-nodejs#243]
Also solves many problems when using the SDK from a browser

https://github.com/nylas/nylas-nodejs/blob/e25ffbe4f56b5c8a73ce4511751f44335d5aa161/src/nylas-connection.ts#L1

**Comment by TrySound** [comment]
@AvivonCtrl Node 8 is still supported. This TODO is for major bump.
https://github.com/nylas/nylas-nodejs/blob/main/.travis.yml#L3

**Comment by mrashed-dev** [comment]
Hey @AvivonCtrl thanks for reopening tihs issue! As @TrySound mentioned, due to needing to support Node >= 8 we cannot support native URL until we cut support for Node < 10. Closing this issue, but if you find this answer unsatisfactory please reopen!
