### ISSUE TITLE
v5.5 breaks "Send Raw Mime", RequestOption's json flag is not being honored

### ISSUE THREAD

**Issue by mmattax** [nylas/nylas-nodejs#246]
Version 5.5 is no longer respecting the `RequestOptions`'s `json` value. In `requestOptions` if `options.body` is set, it is automatically JSON stringified regardless of `options.json`: https://github.com/nylas/nylas-nodejs/blob/42a032db709dd172eb2b997fa2d7ed88b3323caa/src/nylas-connection.ts#L125

This appears to have been broke in this commit: https://github.com/nylas/nylas-nodejs/commit/b995b4f4489c09e05f07c810772b7d816399fe4e, when switching to node-fetch.

Because of this version 5.5 breaks "Send Raw Mime" as documented here: https://developer.nylas.com/docs/developer-tools/sdk/javascript-sdk/#send-raw-mime. As you can see, there is a `json` flag set to false when this.rawMime is set, and flipped to true otherwise:

https://github.com/nylas/nylas-nodejs/blob/42a032db709dd172eb2b997fa2d7ed88b3323caa/src/models/draft.ts#L78

When the request is made, the raw mime content is stringified to JSON and the resulting API call fails. To make matters worse, we've been passing a `Buffer` object which isn't JSON serializable. Even if I was passing a string for `options.body`, running it through `JSON.stringify` would still not work.

I tried to make a PR, by simply changing the logic to:

```typescript
if (options.formData) {
  ...
} else if (options.body && options.json) {
  options.body = JSON.stringify(options.body);
}
```

but this seemingly breaks some calendaring unit tests.

**Comment by mrashed-dev** [comment]
Thanks for opening the issue and pull request, we'll take a look at this!
