### ISSUE TITLE
Expose the conferencing field for the Event resource

### ISSUE THREAD

**Issue by mateorider** [nylas/nylas-nodejs#256]
**Is your feature request related to a problem? Please describe.**
Our users need to be able to view conferencing details for their events (ie meeting URL and meeting code, which can be used to query the provider's api for even more details). When hitting the GET /events endpoint via curl, the `conferencing` field is returned on the events where it exists. When using the node SDK (ie `nylas.events.list()`) the response does not include the `conferencing` attribute.

**Describe the solution you'd like**
Adding the `conferencing` object to the `Event` class definition.

**Describe alternatives you've considered**
I can still get that attribute in the response data from Nylas if I use other http clients (eg axios).

**Comment by mrashed-dev** [comment]
Hey @mateorider thanks for opening the issue, we will investigate and address this feature request!
