### ISSUE TITLE
JSON.stringify removes id field from the message

### ISSUE THREAD

**Issue by igorlesnenko** [nylas/nylas-nodejs#266]
**Describe the bug**

JSON.stringify removes id field from the message.

**To Reproduce**

- Fetch a thread with messages array included
- Call JSON.stringify(thread.messages)
- See messages have no `id`

**Expected behavior**

`id` should not be removed

**Comment by mrashed-dev** [comment]
Thanks for opening this issue, we will take a look at it!

**Comment by mrashed-dev** [comment]
@igorlesnenko we found what the issue was, it had to do with our `toJSON` function and the way `JSON.stringify` was invoking it. The fix should be included in the next release!
