### ISSUE TITLE
Android 10 Drak Mod Permission Issue

### ISSUE THREAD

**Issue by Khandaker869188** [nylas/nylas-nodejs#278]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mrashed-dev** [comment]
Hey @Khandaker869188 thanks for opening this issue! It looks like you didn't fill any of the questions, can you describe your feature request please? Thank you!

**Comment by mrashed-dev** [comment]
Closing this issue as there hasn't been any response or added details.
