### ISSUE TITLE
Add phone_number to Event-Participant model

### ISSUE THREAD

**Issue by art-zcare** [nylas/nylas-nodejs#303]
**Is your feature request related to a problem? Please describe.**
We would like to save a phone_number to calendar event participants for SMS purposes and future contact.

**Describe the solution you'd like**
When creating an event, I'd like to create an event participant with a phone number field

**Describe alternatives you've considered**
Alternatively I could store this phone number in the metadata field on the appointment, but i have to manage each participant.

**Additional context**

- The Event POST API allows a participant to added with a phone_number via https://developer.nylas.com/docs/api/#post/events
- Expecting phone_number to be on this model https://github.com/nylas/nylas-nodejs/blob/main/src/models/event-participant.ts#L4

**Comment by mrashed-dev** [comment]
Thanks for opening this ticket, we will look into adding this field very soon!

**Comment by mrashed-dev** [comment]
Fixed as part of #305, will be released in the next version sometime this week.
