### ISSUE TITLE
Question: is there any typings for webhooks?

### ISSUE THREAD

**Issue by KazimirPodolski** [nylas/nylas-nodejs#311]
I'm trying to setup webhooks endpoints, and I cannot find any types corresponding to webhooks' payloads, e.g. https://developer.nylas.com/docs/developer-tools/webhooks/available-webhooks/#message-created.

Is there any types available for webhoook deltas?

**Comment by mrashed-dev** [comment]
@KazimirPodolski Thanks for opening this ticket! One of our upcoming feature development tasks for this SDK is to improve delta support. Can you describe to me your use case were trying to achieve with the SDK? Are you running the webhook app provided in the SDK? Or are you running a webhook in your own app and require typing/models to help with deserializing? Thanks!

**Comment by KazimirPodolski** [comment]
@mrashed-dev We're just started integrating Nylas for managing user's emails inside our app. Webhook is of our app, it would be nice to have typings for webhooks payloads. Actually errors would be nice too, e.g. Hosted Auth errors.

**Comment by mrashed-dev** [comment]
@KazimirPodolski Thanks for your response! Webhook Notification typing is planned for the SDK for an upcoming release so we got you covered there! Regarding errors, we usually just parse the details in the error thrown by the API and the SDK throws a `NylasApiError` Error type with the details from the error payload (see: #236). Do you have an example of what you would be looking for in terms of the SDK having support for Hosted Auth errors for example?

**Comment by KazimirPodolski** [comment]
`NylasApiError` should do it for us, I'll take a closer look, thanks.

**Comment by mrashed-dev** [comment]
@KazimirPodolski We have introduced some new models that would cover all combinations of Webhook Notifications/deltas! It should be included in the next release coming soon. Below is a snippet that reflects the models, typing and type strictness of these new models:

```javascript
webhookNotification: WebhookDelta[] = new WebhookNotification().fromJSON(webhookNotificationJSON);
/*
* Available Fields for WebhookNotification:
* WebhookNotification.deltas: WebhookDelta[]
 */

const webhookDelta: WebhookDelta = webhookNotification.deltas[0];
/*
* Available Fields for WebhookDelta:
* WebhookDelta.date: Date
* WebhookDelta.object: string
* WebhookDelta.type: string
* WebhookDelta.objectData: WebhookObjectData
 */

const webhookDeltaObjectData: WebhookObjectData = webhookDelta.objectData;
/*
* Available Fields for WebhookObjectData:
* WebhookObjectData.id: string
* WebhookObjectData.accountId: string
* WebhookObjectData.namespaceId: string
* WebhookObjectData.object: string
* WebhookObjectData.objectAttributes?: WebhookObjectAttributes
* WebhookObjectData.metadata?: MessageTrackingData
 */

const webhookDeltaObjectAttributes: WebhookObjectAttributes = webhookDeltaObjectData.objectAttributes;
/*
* Available Fields for WebhookObjectAttributes:
* WebhookObjectAttributes.action?: string
* WebhookObjectAttributes.jobStatusId?: string
* WebhookObjectAttributes.threadId?: string
* WebhookObjectAttributes.receivedDate?: Date
*/

const webhookMessageTrackingData: MessageTrackingData = webhookDeltaObjectData.metadata;
/*
* Available Fields for MessageTrackingData:
* MessageTrackingData.senderAppId: number
* MessageTrackingData.messageId: string
* MessageTrackingData.payload: string
* MessageTrackingData.threadId?: string
* MessageTrackingData.replyToMessageId?: string
* MessageTrackingData.count?: number
* MessageTrackingData.fromSelf?: boolean
* MessageTrackingData.timestamp?: Date
* MessageTrackingData.linkData?: LinkClickCount[]
* MessageTrackingData.recents?: LinkClick[]
 */

const linkData: LinkClickCount = webhookMessageTrackingData.linkData[0];
/*
* Available Fields for LinkClickCount:
* LinkClickCount.url: string
* LinkClickCount.count: number
 */

const recents = webhookMessageTrackingData.recents[0];
/*
* Available Fields for LinkClick:
* LinkClick.id: number
* LinkClick.ip: string
* LinkClick.userAgent: string
* LinkClick.timestamp: Date
* LinkClick.linkIndex?: number
 */
```
