### ISSUE TITLE
"npm install" not getting the last commit

### ISSUE THREAD

**Issue by slava-tre** [nylas/nylas-nodejs#32]
`npm install nylas` not grabbing the last update from `master` branch..
Commit: https://github.com/nylas/nylas-nodejs/commit/de7f639c9e773b0322e6e3571a5a5cdd927ea72b
FYI @khamidou

**Comment by khamidou** [comment]
Thanks for opening a ticket --- I'm looking into this.

Cheers,

k

**Comment by TimFletcher** [comment]
If I run `npm install nylas --save-dev` I get `"nylas": "^2.1.0"` in my `package.json`. There's been 25 commits since that release. Can someone please publish a new version to NPM?

Currently installing with `"nylas": "git+https://git@github.com/nylas/nylas-nodejs.git"` in my `package.json`

**Comment by khamidou** [comment]
Hi there!

Thanks for your patience. I've just published version 2.2.0 of this library --- please let me know if you have any issue.

Cheers,

k

**Comment by TimFletcher** [comment]
Thank you!
On Thu, Jun 2, 2016 at 3:41 PM Karim Hamidou <notifications@github.com>
wrote:

> Hi there!
>
> Thanks for your patience. I've just published version 2.2.0 of this
> library --- please let me know if you have any issue.
>
> Cheers,
>
> k
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/nylas/nylas-nodejs/issues/32#issuecomment-223431397>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAEcuMxEVzABC8aQeFK-ZuC03q3-35nXks5qH04PgaJpZM4IY46t>
> .
>
-- 
--
Tim Fletcher
https://touchmail.io
https://www.linkedin.com/in/timothyafletcher
+1.780.200.9392
