### ISSUE TITLE
Incorrect type for SchedulerBookingOpeningHoursProperties.days

### ISSUE THREAD

**Issue by sunil-zaya** [nylas/nylas-nodejs#328]
**Describe the bug**
In "Create a Scheduling Page" API, under config > booking > opening_hours, "days" is required to be an array of strings. But in the SDK, "days" is declared as a string.

**To Reproduce**
The following code will trigger a Typescript error:
```
  const config = new SchedulerConfig({
    booking: {
      openingHours: [{
        days: ["M", "T", "W", "R", "F"],
      }],
    },
  });
```

**Expected behavior**
"days" should be declared as string[] instead.

**SDK Version:**
6.2.0

**Comment by mrashed-dev** [comment]
@sunil-zaya Thank you for submitting this issue, we are taking a look at this!
