### ISSUE TITLE
Expose sending errors

### ISSUE THREAD

**Issue by khamidou** [nylas/nylas-nodejs#33]
When an SMTP error occurs when sending a message, the Nylas API exposes it in the `server_error` field. We should expose it in the exception.

**Comment by mhwheeler** [comment]
Thanks for filing this for me. Eagerly awaiting resolution. Failing to send mail is a critical error in any email application.

**Comment by qbalin** [comment]
+1

**Comment by mccolin** [comment]
Yes! Would love to know if it's a Nylas-to-SMTP connection error, a failure in the request, something that will forever fail, or something that can be retried.

**Comment by jackiehluo** [comment]
Fixed in 4.0.0!
