### ISSUE TITLE
`WARNING: SDK version may not support your Nylas API version` after upgrading Nylas Node SDK to 6.3.1

### ISSUE THREAD

**Issue by ederski** [nylas/nylas-nodejs#346]
**Describe the bug**
After updating the Nylas Node SDK package to version 6.3.1, we get the following warning:
```
WARNING: SDK version may not support your Nylas API version. SDK supports version 2.5 of the API and your application is currently running on version 2.2 of the API.
```
I found this warning in the Nylas docs [here](https://developer.nylas.com/docs/developer-tools/api/versioning/#sdk), but the suggested solution is to upgrade the SDK version, and the SDK version 6.3.1 is already the latest version.

**To Reproduce**
Update Nylas Node SDK to 6.3.1 and open application. The following warning is logged in the console:
```
WARNING: SDK version may not support your Nylas API version. SDK supports version 2.5 of the API and your application is currently running on version 2.2 of the API.
```

**Expected behavior**
The warning message and/or [Nylas documentation](https://developer.nylas.com/docs/developer-tools/api/versioning/#sdk) should provide an actionable way to update the API version.

**SDK Version:**
6.3.1

**Comment by mrashed-dev** [comment]
Hello @ederski! Thanks for opening this issue. The error message states that your application is currently configured to target v2.2 of the API, while the latest version of the SDK offically supports v2.5. To avoid this message, you can upgrade the API version being targetted by your Nylas application by heading to https://dashboard.nylas.com, going to the "App Settings" tab, and setting the "API Version" to 2.5. 

Let me know if that solves your issue!

**Comment by ederski** [comment]
Thanks for clarifying! That does solve my issue :) And I now see that updating the API version in the nylas developer dashboard is mentioned in the [Errors section](https://developer.nylas.com/docs/developer-tools/api/versioning/#errors). I would also suggest mentioning it in the SDK section [here](https://developer.nylas.com/docs/developer-tools/api/versioning/#sdk) so that it's a bit more obvious.

**Comment by mrashed-dev** [comment]
@ederski Glad I could help! I will close this issue but I'll also forward your feedback to the internal docs team to better clarify the SDK section re: API versioning.

**Comment by ederski** [comment]
Hi! I updated our API version in the dashboard to 2.5 for our dev application but I am still seeing this error when I run locally using nylas package version 6.3.2.

```
WARNING: SDK version may not support your Nylas API version. SDK supports version 2.5 of the API and your application is currently running on version 2.2 of the API.
```

Did I miss something?
