### ISSUE TITLE
Drafts: it is not possible to know if the sending was successful or failed

### ISSUE THREAD

**Issue by dgaletto** [nylas/nylas-nodejs#356]
**Describe the bug**
when trying to send an email, if the payload is long then nothing is returned. Neither error nor promise is resolved

**To Reproduce**
Create a draft, send a long body

https://gist.github.com/dgaletto/6511cd780574f8060af347816ef01529

**Expected behavior**
execute the callback or return a promise

**SDK Version:**
SDK >= 6.3.x

**Additional context**
The error was introduced in the following line: 
https://github.com/nylas/nylas-nodejs/pull/339/files#diff-2de4f9bb82a400d2734c75d30d64883eec745110373fcde2c3e46fea7d3eb325L305

**Comment by dgaletto** [comment]
the easy fix could be to simply re-add that line, but I see that in the PR there was a justification as to why it should be removed.
anyway it seems strange to me that the response returns empty in these cases

**Comment by mrashed-dev** [comment]
@dgaletto Thanks for opening this issue! I have tried to reproduce it on my end and I do see that the email sends every time. However, most times the response as you noted is empty with no message ID. _Sometimes_ I do see the message ID and the full response. I'll investigate the intermittence of this issue and get back to you on it, thanks!

**Comment by mrashed-dev** [comment]
Hey @dgaletto! We've released a new version of the Node SDK v6.4.1 which includes a fix to a bug that affected operations that received data from the API. Let me know if you still encounter this issue after upgrading. Thanks!
