### ISSUE TITLE
Unable to delete drafts

### ISSUE THREAD

**Issue by dpikt** [nylas/nylas-nodejs#36]
For a delete request, the API requires that the draft version number be included in the request body. As far as I can tell, there's no way to do this yet.

Ideally, this code would work:
`Nylas.with(access_token).drafts.delete(id, {"version": draft.version});`

But this adds the version number as a query string rather than putting it in the request body.

**Comment by khamidou** [comment]
Good point, I'll try to fix this soon.

**Comment by fabiomargarido** [comment]
This is also a problem when trying to send a saved draft.
