### ISSUE TITLE
Unexpected issues importing models - `new Event` results in `Event is not a constructor`

### ISSUE THREAD

**Issue by kylekampy** [nylas/nylas-nodejs#360]
**Describe the bug**
A project I'm working on is using Nylas and we're trying to update to 6.x versions of the SDKs. As part of this, we found strange issues _at runtime_ that don't show up as Typescript issues.

Specifically, we'll import the model we need like this:
```js
import Event from "nylas/lib/models/event.js";
```

And then later we try to build an `Event`:
```js
const event = new Event(nylas, {
    calendarId: scope.calendarId,
    description: appointment.description || undefined,
    location: appointment.location.getText(),
    readOnly: true,
    title: appointment.title,
    when: {
        endTime: appointment.endsAt.unix(),
        startTime: appointment.startsAt.unix(),
    },
});
```

The typings for this will all be fine and happy. But when we actually run it we get:
```
Event is not a constructor
```

**To Reproduce**
I've created a small repro repo to make this easier to show: https://github.com/kylekampy/nylas-import-bug/blob/main/index.ts

I've ensured I'm running latest Typescript (4.7.3), latest Nylas SDK (6.4.1), and latest Node LTS (16.15.1)

That repro repo is using yarn, but I've verified using npm instead also doesn't change anything.

We've tried a few other ways of importing, that I've included in the comments in there. None fix it.

The only way to actually build an Event that I've found is to use `Event.default`, like so:
```ts
const event = new (Event as any).default(nylas, {
    calendarId: scope.calendarId,
    description: appointment.description || undefined,
    location: appointment.location.getText(),
    readOnly: true,
    title: appointment.title,
    when: {
        endTime: appointment.endsAt.unix(),
        startTime: appointment.startsAt.unix(),
    },
});
```

But then we lose out on useful typing, and have to cast to `any` (and back).

**Expected behavior**
I would expect that importing the model would result in Event being the default object, not the parent containing both `ICSMethod` and `default`.

**SDK Version:**
6.4.1

**Additional context**
I'm assuming this is some kind of project setup issue. But I'm a little stumped on where exactly the problem is stemming from. The project we encountered this on is fairly large, and Nylas is the only dependency out of 60+ that we've encountered this issue with.

Thanks so much for any helps or tips anyone can provide. I greatly appreciate it!

**Comment by kylekampy** [comment]
Thanks for your quick reply @mrashed-dev!

I changed the import logic to look like this:
```js
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const { default: Event } = require("nylas/lib/models/event");
```

This works! But it loses all Typescript information by being imported that way, unfortunately. The other caveat is that it's just not obvious that we have to go through these extra steps for importing this particular library. When we add a `new Event` to a file without an import, VSCode will auto-add the import as `import Event from "nylas/lib/models/event.js"`, which will all look fine until we try to run it and end up with `Event is not a constructor` issues.

I'm curious to learn more about the CJS importing from ES piece. We use a number of other dependencies (lodash, moment, etc) that are also CJS and can be imported "normally" without having to be required in. Do you happen to know what they might be doing differently to make that possible? When we moved to ES, our understanding was that ES can import from ES and CJS, but being a CJS project would mean we wouldn't be able to import ES modules (which some of our dependencies had moved exclusively to, dropping support for being imported from CJS).

Thank you for your help.

**Comment by kylekampy** [comment]
I'm sorry, I was wrong. Moment and lodash appear to be using import/export at this point. I found a different example of a library we use that's CJS, yet we can import: node-auth0: https://github.com/auth0/node-auth0

**Comment by mrashed-dev** [comment]
@kylekampy Thanks for your messages, let me take a look into this and get back to you on this topic.

**Comment by mrashed-dev** [comment]
@kylekampy Just an update, we are looking into having ESM support for the upcoming major release. This request has been tracked internally so I'm going to close the ticket for now but once we have it implemented I'll make sure to leave a note in this issue. Thanks!

**Comment by kylekampy** [comment]
Sounds good. Thank you!
