### ISSUE TITLE
No response on ```.messages.list({ in: 'inbox' })```

### ISSUE THREAD

**Issue by amansharmaagami** [nylas/nylas-nodejs#370]
Whenever I fetch the messages from Nylas SDK it does not give response from function.

However, it shows the 200 success in API logs.
I'm sharing the screenshot of API log

![image](https://user-images.githubusercontent.com/72781505/174234739-8a77651c-426e-4a16-895f-1ccff13f9443.png)

**SDK Version:**
6.4.1

**Comment by amansharmaagami** [comment]
Same thing happening on ```.messages.find(messageId);```

**Comment by mrashed-dev** [comment]
Hey @amansharmaagami! Thanks for opening this issue, we're going to take a look and get back to you on this.

**Comment by amansharmaagami** [comment]
Its been 10 days our SaaS depends on the SDK, should we go ahead & implement API instead?

**Comment by amansharmaagami** [comment]
@mrashed-dev 

- Yes we are able to get the response using API.
- We haven't test old SDK version.
- We have following code snippet.

``` 
const Nylas = require('nylas');
const nylas = Nylas.with(--access-token--);
function getEmails (req, res) {
  try {
       const emails = nylas.messages.list({ in: 'inbox' });
       res.send(emails);
  } catch (err) {
      res.status(500).send(err);
  }
}


function getEmail (req, res) {
  try {
       const email = nylas.messages.find(req.params.id);
       res.send(email);
  } catch (err) {
      res.status(500).send(err);
  }
}

```


It is worth noticing :- We are not passing any limit here, can it be network issue ?
also the behaviour is only for some specific emails, however we are not able to what kind of specific emails.
Sometimes inbox is working fine, then an email arrives in the inbox it is unresponsive now.

**Comment by amansharmaagami** [comment]
Do SDK fetch more than 100 messages on a request?
because API has default limit of 100.

**Comment by mrashed-dev** [comment]
@amansharmaagami Yes, the SDK doesn't have any pagination support at the moment so it fetches all entries that match. Which means, for example, if an account has 200 emails it will fetch all 200. We're working on adding this feature in the next major release in order to keep parity and behaviour aligned with the API.

**Comment by ashryanbeats** [comment]
Hi @amansharmaagami. I'm sorry to hear that you've been having trouble. I've contacted our support team to see what we can do to diagnose the problem and recommend next steps.

**Comment by mrashed-dev** [comment]
@ashryanbeats thanks for setting up the support ticket.

Closing this ticket, @amansharmaagami thanks for your patience on this. Don't hesitate to reach out again if you encounter any other issues!

**Comment by amansharmaagami** [comment]
Now, We are using the API with limit so current implementation is doing fine.
Thanks for following up much appreciated.
