### ISSUE TITLE
How to get the message body after the webhook is triggered

### ISSUE THREAD

**Issue by alphonse92** [nylas/nylas-nodejs#409]
I wrote it as a bug because there is no option for questions.

How to get the message body after the webhook is triggered?

What my webhook received is: 

```
'{"deltas": [{"date": 1669655971, "object": "message", "type": "message.created", "object_data": {"namespace_id": "92e21jxr1a84ue0quhkx915vy", "account_id": "92e21jxr1a84ue0quhkx915vy", "object": "message", "attributes": {"thread_id": "b84qxxizragdt67r5s6utowuz", "received_date": 1669655961}, "id": "4ps70cry4088q96n1pvf11dko", "metadata": null}}]}'
```

But I had not found how to get the message's body.

**Comment by alphonse92** [comment]
I found it here: https://developer.nylas.com/docs/api/#get/messages/id

**Comment by relaxedtomato** [comment]
Hi @alphonse92 - thanks for following up and closing. For all webhooks, you will need to use the specific API (email, or calendar) to retrieve the full body/data. The webhook provides limited information related to the type of event and relevant IDs.

Feel free to reach out if you have more questions 🙌
