### ISSUE TITLE
Allow a timeout for http requests

### ISSUE THREAD

**Issue by philiiiiiipp** [nylas/nylas-nodejs#421]
**Is your feature request related to a problem? Please describe.**
We see that some requests are taking forever to complete (more than 900s) because of the underlying email server timing out. In our case we use aws lambda to send emails which with a maximum runtime of 900s is not happy.

**Describe the solution you'd like**
We would like to hand a timeout to the nylas sdk which gets forwarded to `node-fetch` so we can handle long running calls appropriately.

I can see this to work either globally via the `NylasConnection` or the `NylasConfig` doing something like
```
import Nylas from 'nylas';

Nylas.config({
  clientId: '',
  clientSecret: '',
  httpOptions: {
    timeout: 3000,
    connectTimeout: 1000,
  },
});
```

or via the individual calls to `send` etc. I see the option via the `.config` easier because the sdk allows for a callback and adding some options to it would become a bit cumbersome.

**Comment by mrashed-dev** [comment]
@philiiiiiipp Thanks for opening this issue. We will take a look at implementing this feature and report back with updates. Thanks!

**Comment by mrashed-dev** [comment]
Hey @philiiiiiipp, we are looking into adding this feature for the Node SDK - can you expand on the difference between `timeout` and `connectTimeout`? Thanks!

**Comment by philiiiiiipp** [comment]
I copied this from the `aws-sdk` I think there they distinguish between a connectTimeout e.g. ssl handshake etc. and the actual call timeout. They also offer mechanisms to retry based on those timeouts.

However, I feel for the `nylas-sdk` that would not be necessary, also given that `node-fetch` does not easily allow you to do this as far as I know. 

For us a `timeout` option would already be a massive improvement.

**Comment by mrashed-dev** [comment]
@philiiiiiipp thank you for your response and your (separate) PR, will look into adding this feature now and will review & merge your PR as well. Thanks for your contributions!

**Comment by mrashed-dev** [comment]
@philiiiiiipp The feature has been implemented and should be part of tomorrow's release! Thanks for your patience. To use the timeout feature, pass in the extra `timeout` configuration option:

```js
const Nylas = require('nylas');


// Initialize an instance of the Nylas SDK using the client credentials and timeout
Nylas.config({
  clientId: "CLIENT_ID",
  clientSecret: "CLIENT_SECRET",
  timeout: 60 // 60 second timeout
});
```
