### ISSUE TITLE
Nylas cli as docker image

### ISSUE THREAD

**Issue by pgsnimble** [nylas/nylas-nodejs#435]
**Is your feature request related to a problem? Please describe.**

No, isn't a problem

**Describe the solution you'd like**

I would like to run the nylas-webhooks locally as a docker container

**Describe alternatives you've considered**

I've created this [docker image](https://github.com/pgsnimble/nylas-webhooks) that allow us to run the nylas cli as a docker image, however would be nice to have a oficial image from Nylas team

**Additional context**

**Comment by mrashed-dev** [comment]
Hey @pgsnimble, thanks for submitting this cool idea! I've added this idea to our [Nylas Roadmap](https://roadmap.nylas.com/tabs/13-in-progress) board and if it gets picked up you'll be able to see it and track its progress!
