### ISSUE TITLE
fastify / nestjs middleware support

### ISSUE THREAD

**Issue by ianzone** [nylas/nylas-nodejs#436]
this [express middleware](https://github.com/nylas/nylas-nodejs/pull/367) PR looks amazing, a nest-fastify middleware is very desired

**Comment by mrashed-dev** [comment]
@ianzone Thank you for expressing your interest in the express middleware and expanding our middleware reach. Currently we've decided on another direction but I've created this idea in our [Nylas Roadmap](https://roadmap.nylas.com/tabs/13-in-progress). If this idea picked up you'll be able to see it right on that roadmap and track the progress!
