### ISSUE TITLE
add type check for the list function

### ISSUE THREAD

**Issue by ianzone** [nylas/nylas-nodejs#438]
there is no property check for all endpoints' list functions currently. 
![image](https://user-images.githubusercontent.com/20043230/227524194-2995a225-21f5-4fc4-adbf-164cb41a2fcd.png)

**Comment by mrashed-dev** [comment]
@ianzone Thank you for opening this ticket. We are planning for better type support for all resource operations like list, creating, updating, etc. where you will get something similar to `List<Contact>` as a return type for this function (for example, design not finalized). This will come in the next version of the Nylas Node SDK v7, so stay tuned for more updates! Thank you again for your suggestion.
