### ISSUE TITLE
add "update" method on RestfulModelCollection class

### ISSUE THREAD

**Issue by ianzone** [nylas/nylas-nodejs#448]
**Is your feature request related to a problem? Please describe.**
currently, when you update an entity you need to fetch it first. it increases the response latency and points of failure. 

**Describe the solution you'd like**
add an update method on the  RestfulModelCollection class to do one time PUT request. 
```
update(props: PartialPropertiesWithID) : Promise<T>
```

**Comment by mrashed-dev** [comment]
Thanks for opening this issue @ianzone! We are actually integrating the exact feature you are requesting in the next major release of the SDK as we aim to make the SDK more immutable and we will have properties that are specific to creating, fetching, updating, and deleting all of these resources like Calendars, Events, etc.

We don't have an exact timeline for when this will be released but it should be coming soon, when we have more details to share we will let you know!
