### ISSUE TITLE
Don't use console.error

### ISSUE THREAD

**Issue by yulianovdey** [nylas/nylas-nodejs#456]
**Describe the bug**
There is a `console.error` call [here](https://github.com/nylas/nylas-nodejs/blob/ff9911a372a51724acc902c52f490f288c21aada/src/nylas-connection.ts#L319) we can't route through our logging handler. This is particularly an issue with Datadog because `err.stack` ends up including new lines and every line ends up as a separate log statement.

**To Reproduce**
We see this happen whenever a server error is returned from Nylas.

**Expected behavior**
nylas-nodejs does not log anything directly, and instead offers an option to toggle this behavior, or provides a way to inject a logger.

**SDK Version:**
Latest.

**Additional context**
It looks like calls to `console.log` were removed in [3.1.1](https://github.com/nylas/nylas-nodejs/blob/4b370911865fb36445fa6fc8dc6233645ffc6de9/CHANGELOG.md#311--2017-10-06), but this error log was kept in.

Thank you!

**Comment by mrashed-dev** [comment]
Hey @yulianovdey! Thanks for opening this issue. We can remedy this by removing that `console.error` line and instead we can just intercept the error and throw an SDK specific error with the original message embedded with it. We'll fix this and include it in a future update. Thanks for opening this issue!

**Comment by relaxedtomato** [comment]
approach to fix: 
- Need to remove all instance of console.error lines
- Add linting rule to prevent console.errors from being added to the code base
- Create a new error called NylasSdkError
- Replace the console.error indicated by the user with

**Comment by Siddikpatel** [comment]
> approach to fix:
> 
> * Need to remove all instance of console.error lines
> * Add linting rule to prevent console.errors from being added to the code base
> * Create a new error called NylasSdkError
> * Replace the console.error indicated by the user with

Is it ok if the new error class is inside the src directory? And also, do you need to replace all those 'console.error` lines with newly created error class? throw the error directly in the system?

**Comment by mrashed-dev** [comment]
Thanks for your patience @yulianovdey, we now remove the console calls and allow you to pass in a logger if you want to receive messages.
