### ISSUE TITLE
m is not a constructor

### ISSUE THREAD

**Issue by denfield-daveyonmayne** [nylas/nylas-nodejs#460]
Using v6.10.0 I got an error for `new EmailParticipant({..})`. A basic usage gives the error:

```ts
import EmailParticipant from 'nylas/lib/models/email-participant.js';

// Gives an error m is not a constructor
new EmailParticipant({email: 'foo', name: 'bar'})

```

Edited: I'm importing in a TypeScript file with compilerOptions:

```ts
{
  "compilerOptions": {
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "disableSizeLimit": true,
    "allowJs": true,
    "checkJs": false
  }
}
```

**Comment by relaxedtomato** [comment]
Hi @denfield-daveyonmayne - thanks for the message, is the purpose of the code shared to send an email?

**Comment by relaxedtomato** [comment]
Ah okay, I see, the code sample is creating email participants to send emails to.

**Comment by denfield-daveyonmayne** [comment]
Hi yes, to send a message [per docs](https://developer.nylas.com/docs/api/v2/#post/send).

**Comment by denfield-daveyonmayne** [comment]
Think I see a potential issue. I'm importing that `.js` file in a TypScript file. This may be the issue.

**Comment by relaxedtomato** [comment]
So swapping import for require works:

`const { default: EmailParticipant } = require('nylas/lib/models/email-participant');`

and 

`const sendTo = new EmailParticipant({ email: to });`

**Comment by denfield-daveyonmayne** [comment]
Hi @relaxedtomato in this application, we cannot use require. Is there another workaround using `import`?

**Comment by relaxedtomato** [comment]
Okay, will spin up a TypeScript project with your config and take a look soon 👍

**Comment by relaxedtomato** [comment]
Sharing a [related issue](https://github.com/nylas/nylas-nodejs/issues/360) for context. I don't see a straightforward path until we support ESM.

cc: @mrashed-dev

**Comment by relaxedtomato** [comment]
@denfield-daveyonmayne - let me know if the following works, going to test with your TS config next:


```

import EmailParticipant from "nylas/lib/models/email-participant.js";

const sendTo = new EmailParticipant.default({ email: 'email@email.com' });
```

**Comment by relaxedtomato** [comment]
I had to modify the TS config (first two items)

```
{
  "compilerOptions": {
    "target": "es2017",
    "module": "es2022",
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "disableSizeLimit": true,
    "allowJs": true,
    "checkJs": false
  }
}
```

**Comment by denfield-daveyonmayne** [comment]
Hi @relaxedtomato did you got it working on your end? I'm getting

```ts
 error TS2339: Property 'default' does not exist on type 'typeof EmailParticipant'
```
I've also modified my `compilerOptions` as what you have.

**Comment by denfield-daveyonmayne** [comment]
If you guys are working on an ES import then I'd use axios where needed until then. I'll close this thread and thanks for your time.

**Comment by relaxedtomato** [comment]
Sounds good @denfield-daveyonmayne, just an update: @mrashed-dev from our SDK team has shared that ESM support is going into active development in a sprint soon. We'll keep you posted!
