### ISSUE TITLE
Bad Request when update the event

### ISSUE THREAD

**Issue by ianzone** [nylas/nylas-nodejs#470]
Source code
```typescript
import { getConnection } from '../client';

const nylas = getConnection()

async function update(id:string) {
  const event = await nylas.events.find(id)
  event.title='new title'
  const res = await event.save()
  console.log(res)
}

update('et0kr6fovbr5syanag4f7pf7w')
```
Error msg `Bad Request: Visibility cannot have the value ''`

**Comment by ianzone** [comment]
the sdk should omit the event.visibility when sending the update request.

**Comment by relaxedtomato** [comment]
@ianzone have you tried specifying 'null' as default, does that work for you?

**Comment by ianzone** [comment]
> @ianzone have you tried specifying 'null' as default, does that work for you?

There is always a remedial measure, but my point is the SDK should do the job as the docs described.
![image](https://github.com/nylas/nylas-nodejs/assets/20043230/0201ad99-2b28-4447-874e-6c788a6bb600)

**Comment by relaxedtomato** [comment]
note on fix: Need to ensure to nullify visibility before sending the payload if visibility is an empty string
