### ISSUE TITLE
Timeout is always 150ms

### ISSUE THREAD

**Issue by kgtupelo** [nylas/nylas-nodejs#489]
**Describe the bug**
The provided timeout is not respected. When providing a timeout, it is always defaulting to 150ms.

https://github.com/nylas/nylas-nodejs/blob/cb42d16b3c597d4297e71303066f2266a66084ee/src/nylas-connection.ts#L236-L241

**Expected behavior**
The timeout we provide to be respected.

**SDK Version:**
6.10.0

**Comment by Siddikpatel** [comment]
Hi. Can you check the PR #490 ? It seems to fix your issue.

**Comment by mrashed-dev** [comment]
Hey @kgtupelo, sorry to see that PR closed. I opened a new PR and the fix will be included in the next release. Apologies for the delay.
