### ISSUE TITLE
Cannot find module './package.json'

### ISSUE THREAD

**Issue by ryanmcclure4** [nylas/nylas-nodejs#53]
Versions 3.0.1 and 3.0.2 are both throwing the error `Error: Cannot find module './package.json'`, causing node to crash. This seems to be due to the latest commit https://github.com/nylas/nylas-nodejs/commit/bcafb5ee8d01230acd41181fd4d0919a2f8a610c

**Comment by jstejada** [comment]
hey @ryanmcclure4 , can you update to version 3.0.2? It should be fixed in that version.
Thanks!

**Comment by jstejada** [comment]
Oh sorry, missed the part that said v 3.0.2 is also throwing the error
