### ISSUE TITLE
messages/send does not support "from" field

### ISSUE THREAD

**Issue by jaencarrodine** [nylas/nylas-nodejs#542]
**Describe the bug**

The "from" user name cannot be set when sending emails.

**To Reproduce**
Some steps involved to reproduce the bug and any code samples you can share.
```
// Helps us with reproducing the error :)
```
await nylas.messages.send({
        identifier: messagingAccountRes.data.grant_id,
        requestBody: {
            to: [{ email: to }],
            subject: subject,
            body: body,
            //@ts-ignore
            from: [{ email: <some email address> , name: <some name> }],
        },
    })

**Expected behavior**

BaseCreateMessage should be updated to include from field, from field should be passed to the sent email

**SDK Version:**
Providing the SDK version can help with the reproduction of the issue and to know if a change could have broken something.
7.1.0
**Additional context**

**Comment by mrashed-dev** [comment]
@jaencarrodine thanks for opening this issue! We've opened a PR that should solve this, and will be available in the next release.
