### ISSUE TITLE
unhandled promise rejection - nylas.folders.list() on a gmail account

### ISSUE THREAD

**Issue by xxx** [nylas/nylas-nodejs#56]
Hi,

When making a `nylas.folders.list()` call on a GMail account, there's a rejected promise that can't be caught.

I know this call will always fail on GMail accounts, but I'd like to be able to handle the error within my app. Am I missing something? I've tried both `.catch` and callback style. My handlers are never reached.

**Comment by cdimitroulas** [comment]
There's another unhandled promise rejection which can happen, which is when a user's `account` is deleted from the Nylas dashboard and they try to make a request using their old `access_token`.
