### ISSUE TITLE
cannot set offset parameter in messages.list api ...

### ISSUE THREAD

**Issue by SachinMantra** [nylas/nylas-nodejs#57]
cannot set offset while fetching the messages.... whteva i set in offset field..it always take it to zero...?? i dont know wht n where m doing it wrng.... thanquu

                var nylas = Nylas.with(token);
                nylas.messages.list({offset:10,limit:50},function(err, messages) {
                  console.log(messages)
                })

**Comment by dejitaiza** [comment]
@SachinMantra If you're still looking for a fix to this issue I implemented one in the fork here:

https://github.com/dejitaiza/nylas-nodejs/tree/offset-fix

Also opened a PR in this repo.

**Comment by jackiehluo** [comment]
@dejitaiza Let me know if you get a chance to update the PR and sign our CLA! I would love to get your fix merged.

**Comment by jackiehluo** [comment]
Fixed in 4.0.0!
