### ISSUE TITLE
Property 'name' does not exist on type 'Grant'.ts - Upgrade types

### ISSUE THREAD

**Issue by gsaavedra-srx** [nylas/nylas-nodejs#599]
**Describe the bug**
Property 'name' does not exist on type 'Grant'.ts

**To Reproduce**
```
const grant = await this.nylas.grants.find({ grantId: 'xyz'});
console.log(grant.data.name) // typescript warning on vscode
```

**Expected behavior**
Warning should not be displayed, 'name' property is returned now.

**SDK Version:**
7.5.2

**Comment by SubashPradhan** [comment]
Hey @gsaavedra-srx thanks for reporting this issue, we will get this fixed on the next release.
