### ISSUE TITLE
Delta Stream exponential backoff not working

### ISSUE THREAD

**Issue by kewitz** [nylas/nylas-nodejs#61]
The exponential backoff on Delta Streamer isn't working properly.
It's updating the cursor but not completing the actual connection.
![image](https://user-images.githubusercontent.com/2119706/28833018-855c3840-76b4-11e7-97c8-dd65bd535a92.png)

**Comment by jackiehluo** [comment]
Hey! Thanks for submitting this issue. Could you explain further? What is your expected behavior, and what's happening right now?

**Comment by kewitz** [comment]
Hey @jackiehluo,
This issue is a bit old and I'm not sure if it still exists.
The problem here is that the back-off is not increasing the attempts and as consequence it will never fail.
Also, although it keeps trying to connect to the stream API it actually never succeeds.

**Comment by jackiehluo** [comment]
Got it, thank you for the update! So—I think the delta stream _should_ be working now (it's working in my tests), but if you find that it's still an issue, feel free to let me know, and we'll investigate. Thanks!
