### ISSUE TITLE
MAINTENANCE STATUS

### ISSUE THREAD

**Issue by gregory** [nylas/nylas-nodejs#62]
Hello guys, 

I was just wondering if this was still maintained or if you could use some help to maintain it?
Would be sad to see this forked & maintained by someone else. 
Your API is evolving yet no one maintaining the clients...

**Comment by spang** [comment]
Hi @gregory,

You're absolutely right, we haven't been paying enough attention to this library. We're prioritizing a major rev of the library right now, let us know if you have any requests for the update.
