### ISSUE TITLE
API for Message.sendRaw is weird

### ISSUE THREAD

**Issue by spang** [nylas/nylas-nodejs#66]
Currently, we do not export the `Message` class, making `Message.sendRaw` hard to access.
```
var Nylas = require('nylas');
var accessToken = 'example';
var conn = Nylas.with(accessToken);
var message = 'example';

conn.messages.modelClass.sendRaw(conn, msg);
```

We should expose a better API for interacting with the raw send endpoint.

Maybe we could export the `Message` class, or expose `sendRaw` on `conn.messages` (the latter would be hackish to implement as far as I can tell, though it's nice that it maintains the invariant that all of the SDK's functionality is exposed on the `NylasConnection` object).

**Comment by jackiehluo** [comment]
Fixed in 4.0.0!
