### ISSUE TITLE
StatusCodes swallowing when request had error

### ISSUE THREAD

**Issue by vadzappa** [nylas/nylas-nodejs#70]
https://github.com/nylas/nylas-nodejs/blob/17f7c0b620c55a15858c21eebfc0fa3828e14b98/src/nylas-connection.js#L134

Starting from this line, error handling is made in such a way, that consumer doesn't get any information about the underlying statusCode. While statusCode is essential part of RESTfull applications.

**Comment by annielcook** [comment]
@vadzappa thanks for pointing this out! I just landed a fix for it and will deploy a new version momentarily.
