### ISSUE TITLE
Don't spam the console with warnings if the api does not return a version

### ISSUE THREAD

**Issue by AdriVanHoudt** [nylas/nylas-nodejs#72]
I've seen cases where the api does not return a version.
The SDK will still print warnings in that case https://github.com/nylas/nylas-nodejs/blob/8a96644965b8b8b1b9e61ceffb6d1f91eda19d0a/src/nylas-connection.js#L102
This is something I, as a user of the api, can't fix and is extremely annoying.
If the version mismatches it is totally fine to warn, I even like it that it does that. But in this specific case it is not helpful at all.
Would you take a PR to remove this? Or make it smarter?

**Comment by annielcook** [comment]
Hi @AdriVanHoudt. Our initial idea behind this messaging was to provide users with more information about why things might be behaving weirdly after we added versions to our API. I can see how warning where the api does not return a version is annoying and not helpful. Would you suggest just removing the line 102 to resolve this?

Also, have you noticed a pattern for when the api doesn't return a version?

Thanks for your feedback!

**Comment by AdriVanHoudt** [comment]
Yeah just moving into the `if` would solve it.
I've not noticed a pattern since it just prints the warning with no additional info like the (base) url that was called or something.
