### ISSUE TITLE
Revoking a token through the api

### ISSUE THREAD

**Issue by guillaumecostanza** [nylas/nylas-nodejs#74]
Hello,
do you or will you provider a wrapper for oauth endpoint ?

Thank you

**Comment by AdriVanHoudt** [comment]
Kinda related to https://github.com/nylas/nylas-nodejs/issues/71

**Comment by Gerdie** [comment]
@guillaumecostanza we have a wrapper for the RevokeAll endpoint, which allows you to revoke all of an account's tokens, and optionally specify a token to keep. We are prioritizing more oauth work in the next quarter.
```
Nylas.accounts.find('<accId>').then(acc => {
    acc.revokeAll('<optionalTokenToKeep>').then(resp => console.log(resp));
})
```
