### ISSUE TITLE
close 1.0.1 is deprecated

### ISSUE THREAD

**Issue by AdriVanHoudt** [nylas/nylas-nodejs#79]
Installing Nylas prints
`npm WARN deprecated clone@1.0.1: XSS vulnerability fixed in v1.0.3`
See https://github.com/pvorb/clone#v103
Higher versions then 1.0.3 might even give a small speed boost on newer node versions, see https://github.com/pvorb/clone/commit/20960601fdce84bd8cb5fc3be68820e42d67681d

**Comment by singingwolfboy** [comment]
Resolved by #100.
