### ISSUE TITLE
Published package contains 120MB tags file

### ISSUE THREAD

**Issue by AdriVanHoudt** [nylas/nylas-nodejs#85]
Download https://registry.npmjs.org/nylas/-/nylas-4.2.2.tgz
Extract and you will see the tags file.

I think this is in the .gitignore but it somehow still gets published. Please fix this as this means people have to download and extract the whole thing and it takes up disk space.
`node_modules/nylas` is more than 10x larger then the next package in line in our case.

**Comment by singingwolfboy** [comment]
Resolved by #84
