### ISSUE TITLE
Generates broken HTML

### ISSUE THREAD

**Issue by gunar** [nylas/nylas-nodejs#90]
### Input

```js
  console.log(emailObject)
  const response = await nylas.with(nylasToken).drafts.build(emailObject).send()
  // { to: [ { email: 'REDACTED' } ],
  //   cc: [],
  //   bcc: [],
  //   body: '<div><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABsAAAAaCAIAAADJ6rCnAAAACXBIWXMAAA7EAAAOxAGVKw4bAAADaUlEQVRIiY2Vy44bVRCG/6pza9ttm4xQIhSBxIKHYAfPgQRvjsIKSCYTuz3uyzl1YeGZiNX01LZb3/n+OlXd9NMPP3bdRmpLIW63m36/y7l8/vwxxFRKIrNSNsMw/PzrL+7ubu747Y/f8b8yMxE5nU5v374FEIlIVR3OMXTbrtbWpA7DJcZYvr1zommciGBucHcAhJcr5hgVfjvM3Wur8zLt+p2qXMexlOIiqRQCnED+9OoLxapqamr2+Hi9v79PKZjZ8XjY9TtpreScu1KX+avamiKimjlxYJ6WCQxiTild51GacAjuLiLn89ltVe6ZGGM0IMVk7n2/g/PhcDidz2Lt2B+aSK015mzuRABo3bE2aVVbrDllAh6+PIRAIsIhTNN03B9yf3j48hevo76mVt312xBiXaZheAwMeOz7npin69UdpWQ4+Ss6+EQ0AAAzdWW7KSmV9OXhYRqn4+GQDvucc0jp7s2du4H4lY4yjZMm6XLJMX/37l1kvgyDuW3KxkSGcQLwakVEMyu7vN/2ZLbM86d/P6YQj8fjPM/j9ZpiNFUzpec+3sb8RUczDqF0HYmqtpyiSM2lc9fzaViYAlFt1c2A23ivEZvU0+nkTfddd+h7Bl0uj3muZZv7/U5aE5VSyjNmVRHMzFBVbamk4903w2UoOYYSzLHdbjabblmWeZ4Af7Jb3WvAHCD2/rA/D+dZ6mZTruPITMNFW6sl52Wa3V+x0jeiq3EM0tqn+0+mVuscclykBg6BXFpzEXvGOdbBMYaYchaxy/nU73bkzoA3XazmEJe5unuI8Qbyr9lf6GMI1NrSlUREwzAQoUptJkutY13ARMyq6u7uDndb+2TE99+/n8fxcjlLlZTTJHMbpUpTVxXZdJtAfB2vcDjB1xXBXZdTTOM0EdG+34vZslSHA8EMIEYI6rAnxxUcgPjhzw91rjmXuzd34zSWWFTV/CZErYkJSt4At/lZHUcwg7rSwR1AV7oUY4oR6taEQNrM3Pb7IxzuboCtbiGZublJ/fjP3zmn7XY3Xa8iFmKEGTHc6Hz6bLe7fkXyeLvApkIOt/j4eBERAFqFiFNKkUndbnFfERpR2N1JQEzQwHWutwdmxuQBobm0Knhu5DpxqdUMBmcOopZKcjUzD4GYGOwqTVTotqzw1T/Nfy+ndSa09wNoAAAAAElFTkSuQmCC"></div>',       
  //   subject: 'test',
  //   files: undefined }

```

### Output

![image](https://user-images.githubusercontent.com/7684574/52881558-0b65b080-314c-11e9-9b21-ae0c531c7b63.png)

### The problem

Nylas is adding `3D` to my HTML (which is suspicious since `unescape('%3D') == '='`) which is making images not show up on Gmail (and is costing us business).

Thoughts?

**Comment by Gerdie** [comment]
Hi @gunar this is a MIME encoding mechanic called [quoted-principle](https://en.wikipedia.org/wiki/Quoted-printable) which represents an ascii equals sign as `=3D`. It's not something Nylas adds, and is unlikely to be the reason your images are not rendering. 

Many email providers, gmail included, no longer support base64 encoded images. If you send the above message to a gmail account and a yahoo account, the yahoo account will render your image fine but the gmail account will not. I would suggest attaching images in a better supported way, i.e. hosting the image file online and referencing the url in the src attribute. Please re-open if this does not solve your problem.
