### ISSUE TITLE
why nylas disabled our app

### ISSUE THREAD

**Issue by kudeshiyah** [nylas/nylas-nodejs#99]
![image](https://user-images.githubusercontent.com/17821874/53079985-a7f9cb00-351d-11e9-9fe2-2eadd02844aa.png)

There is no info regarding this in dashboard.
Please Help!

**Comment by pfista** [comment]
Hey @kudeshiyah - please reach out to support@nylas.com with your application_id/client_id email address on file so we can identify your account and see what's going on. Thanks!

**Comment by chulanovskyi-bs** [comment]
@kudeshiyah @pfista, so what was the issue? Is it possible to document somewhere (at API docs probably) the _common_ reasons of that?

**Comment by LuuchoRocha** [comment]
I'm facing this same issue. I'm not the account owner but I'm a developer and I have created two apps for testing and they both were disabled today. I've been using it only for testing :/
